// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json.Linq;

namespace Trip.JinJiang.H5
{

    public class Line2
    {
        public int id { get; set; }
        public string code { get; set; }
        public string name { get; set; }
        public string title { get; set; }
        public string lineCategory { get; set; }
        public string travelBrand { get; set; }
        public string travelAgency { get; set; }
        public string imageUrl { get; set; }
        public string[] tagName { get; set; }
        public string[] departDate { get; set; }
        public double? minPrice { get; set; }
        public double? minPrimePrice { get; set; }
        public string updateTime { get; set; }
        public string productCode { get; set; }
        public string soldoutFlag { get; set; }
    }

}
