// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace Trip.JinJiang.H5
{

    internal partial class linelists
    {
        internal class EsGroup2
        {

            [JsonProperty("groupId")]
            public int GroupId { get; set; }

            [JsonProperty("lineId")]
            public int LineId { get; set; }

            [JsonProperty("salePrice")]
            public int SalePrice { get; set; }

            [JsonProperty("clusterType")]
            public int ClusterType { get; set; }

            [JsonProperty("deadLineTime")]
            public object DeadLineTime { get; set; }

            [JsonProperty("deadLineTimeVal")]
            public string DeadLineTimeVal { get; set; }

            [JsonProperty("departDate")]
            public object DepartDate { get; set; }

            [JsonProperty("leftNum")]
            public int LeftNum { get; set; }
        }
    }

}
