// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace Trip.JinJiang.H5
{

    internal partial class linelists
    {
        internal class Page2
        {

            [JsonProperty("page")]
            public int Page { get; set; }

            [JsonProperty("rows")]
            public int Rows { get; set; }

            [JsonProperty("records")]
            public int Records { get; set; }

            [JsonProperty("total")]
            public int Total { get; set; }

            [JsonProperty("sidx")]
            public object Sidx { get; set; }

            [JsonProperty("sord")]
            public object Sord { get; set; }

            [JsonProperty("search")]
            public bool Search { get; set; }

            [JsonProperty("startRow")]
            public int StartRow { get; set; }

            [JsonProperty("endRow")]
            public int EndRow { get; set; }
        }
    }

}
