// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace Trip.JinJiang.H5
{

    internal partial class linelists
    {
        internal class Line
        {

            [JsonProperty("lineId")]
            public int LineId { get; set; }

            [JsonProperty("lineName")]
            public string LineName { get; set; }

            [JsonProperty("name")]
            public string Name { get; set; }

            [JsonProperty("title")]
            public string Title { get; set; }

            [JsonProperty("destinationInfo")]
            public string DestinationInfo { get; set; }

            [JsonProperty("spotInfo")]
            public string SpotInfo { get; set; }

            [JsonProperty("lineSubjectInfo")]
            public string LineSubjectInfo { get; set; }

            [JsonProperty("destination")]
            public string[] Destination { get; set; }

            [JsonProperty("spot")]
            public string[] Spot { get; set; }

            [JsonProperty("lineSubject")]
            public string[] LineSubject { get; set; }

            [JsonProperty("manualRecommend")]
            public int? ManualRecommend { get; set; }

            [JsonProperty("imageNo")]
            public int ImageNo { get; set; }

            [JsonProperty("brand")]
            public string Brand { get; set; }

            [JsonProperty("agency")]
            public string Agency { get; set; }

            [JsonProperty("days")]
            public int Days { get; set; }

            [JsonProperty("isPromotion")]
            public int IsPromotion { get; set; }

            [JsonProperty("departureMonth")]
            public int[] DepartureMonth { get; set; }

            [JsonProperty("priceScope")]
            public int[] PriceScope { get; set; }

            [JsonProperty("esGroup")]
            public EsGroup2[] EsGroup { get; set; }

            [JsonProperty("point")]
            public double Point { get; set; }

            [JsonProperty("imageUrls")]
            public string[] ImageUrls { get; set; }

            [JsonProperty("lineCategory")]
            public string LineCategory { get; set; }

            [JsonProperty("minPrice")]
            public int MinPrice { get; set; }

            [JsonProperty("tags")]
            public Tag[] Tags { get; set; }

            [JsonProperty("productCode")]
            public string ProductCode { get; set; }

            [JsonProperty("priceScopeAndLine")]
            public string[] PriceScopeAndLine { get; set; }

            [JsonProperty("lineDistrict")]
            public string LineDistrict { get; set; }

            [JsonProperty("originalPrice")]
            public int OriginalPrice { get; set; }

            [JsonProperty("priceExplain")]
            public string PriceExplain { get; set; }

            [JsonProperty("recommend")]
            public string Recommend { get; set; }
        }
    }

}
