// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace Trip.JinJiang.H5
{

    internal partial class linelists
    {
        internal class Tag
        {

            [JsonProperty("id")]
            public object Id { get; set; }

            [JsonProperty("tagType")]
            public object TagType { get; set; }

            [JsonProperty("name")]
            public string Name { get; set; }

            [JsonProperty("tagSource")]
            public object TagSource { get; set; }

            [JsonProperty("lineCount")]
            public object LineCount { get; set; }

            [JsonProperty("createDate")]
            public object CreateDate { get; set; }

            [JsonProperty("updateDate")]
            public object UpdateDate { get; set; }

            [JsonProperty("onLineDiscount")]
            public object OnLineDiscount { get; set; }
        }
    }

}
