// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace Trip.JinJiang.H5
{

    internal partial class linelists
    {

        [JsonProperty("page")]
        public Page2 Page { get; set; }

        [JsonProperty("lines")]
        public Line[] Lines { get; set; }

        [JsonProperty("departureMonths")]
        public DepartureMonth2[] DepartureMonths { get; set; }

        [JsonProperty("brands")]
        public Brand2[] Brands { get; set; }

        [JsonProperty("agencies")]
        public Agency2[] Agencies { get; set; }

        [JsonProperty("priceScopes")]
        public PriceScope2[] PriceScopes { get; set; }

        [JsonProperty("days")]
        public Day[] Days { get; set; }

        [JsonProperty("spots")]
        public Spot2[] Spots { get; set; }

        [JsonProperty("promotions")]
        public Promotion[] Promotions { get; set; }

        [JsonProperty("clusterTypes")]
        public ClusterType2[] ClusterTypes { get; set; }

        [JsonProperty("lineCategorys")]
        public LineCategory2[] LineCategorys { get; set; }

        [JsonProperty("citys")]
        public City[] Citys { get; set; }

        [JsonProperty("priceScopeAndLine")]
        public PriceScopeAndLine2[] PriceScopeAndLine { get; set; }

        [JsonProperty("errorMessage")]
        public object ErrorMessage { get; set; }
    }

}
