// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace Trip.JinJiang.H5
{

    internal partial class linelists
    {
        internal class Spot2
        {

            [JsonProperty("name")]
            public string Name { get; set; }

            [JsonProperty("count")]
            public int Count { get; set; }
        }
    }

}
