// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json.Linq;

namespace Trip.JinJiang.H5
{

    public class PriceScope
    {
        public string name { get; set; }
        public int count { get; set; }
    }

}
