// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json.Linq;

namespace Trip.JinJiang.H5
{

    public class Tag
    {
        public object id { get; set; }
        public int lineId { get; set; }
        public object tagType { get; set; }
        public string name { get; set; }
        public object tagSource { get; set; }
        public object lineCount { get; set; }
        public object createDate { get; set; }
        public object updateDate { get; set; }
        public object onLineDiscount { get; set; }
    }

}
