// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace Trip.JinJiang.H5
{

    partial class SampleResponse3
    {

        [JsonProperty("errorCode")]
        public object ErrorCode { get; set; }

        [JsonProperty("errorMsg")]
        public object ErrorMsg { get; set; }

        [JsonProperty("id")]
        public int Id { get; set; }

        [JsonProperty("lineId")]
        public int LineId { get; set; }

        [JsonProperty("code")]
        public string Code { get; set; }

        [JsonProperty("groupCode")]
        public string GroupCode { get; set; }

        [JsonProperty("name")]
        public string Name { get; set; }

        [JsonProperty("lineTitle")]
        public string LineTitle { get; set; }

        [JsonProperty("departurePlace")]
        public string DeparturePlace { get; set; }

        [JsonProperty("priceInclude")]
        public string PriceInclude { get; set; }

        [JsonProperty("priceExclusive")]
        public string PriceExclusive { get; set; }

        [JsonProperty("payOnlineFlag")]
        public int PayOnlineFlag { get; set; }

        [JsonProperty("scoreRatio")]
        public int ScoreRatio { get; set; }

        [JsonProperty("onlineDiscount")]
        public double OnlineDiscount { get; set; }

        [JsonProperty("departDate")]
        public long DepartDate { get; set; }

        [JsonProperty("returnDate")]
        public long ReturnDate { get; set; }

        [JsonProperty("leftNum")]
        public int LeftNum { get; set; }

        [JsonProperty("prices")]
        public Price[] Prices { get; set; }

        [JsonProperty("vipOnlineDiscount")]
        public double VipOnlineDiscount { get; set; }
    }

}
