// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace Trip.JinJiang.H5
{

    internal partial class SampleResponse3
    {
        internal class Price
        {

            [JsonProperty("id")]
            public int Id { get; set; }

            [JsonProperty("code")]
            public string Code { get; set; }

            [JsonProperty("offerProject")]
            public string OfferProject { get; set; }

            [JsonProperty("offerType")]
            public string OfferType { get; set; }

            [JsonProperty("salePrice")]
            public int SalePrice { get; set; }

            [JsonProperty("agentPrice")]
            public int AgentPrice { get; set; }

            [JsonProperty("vipPrice")]
            public int VipPrice { get; set; }

            [JsonProperty("vipAgentPrice")]
            public int VipAgentPrice { get; set; }

            [JsonProperty("staffPrice")]
            public int StaffPrice { get; set; }

            [JsonProperty("staffAgentPrice")]
            public int StaffAgentPrice { get; set; }
        }
    }

}
