// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json.Linq;

namespace Trip.JinJiang.H5
{

    public class EsGroup
    {
        public int groupId { get; set; }
        public int lineId { get; set; }
        public int salePrice { get; set; }
        public int clusterType { get; set; }
        public object deadLineTime { get; set; }
        public string deadLineTimeVal { get; set; }
        public object departDate { get; set; }
        public int leftNum { get; set; }
    }

}
