// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json.Linq;

namespace Trip.JinJiang.H5
{

    public class Page
    {
        public int page { get; set; }
        public int rows { get; set; }
        public int records { get; set; }
        public int total { get; set; }
        public object sidx { get; set; }
        public object sord { get; set; }
        public bool search { get; set; }
        public int startRow { get; set; }
        public int endRow { get; set; }
    }

}
